# use a .env file to populate the variables in this file
# you can check interpolation with:
# docker compose config
#
services:
  app:
    image: ghcr.io/jkloian/be_the_golf:${APP_VERSION:-latest}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env.production
    ports:
      - "${EXTERNAL_PORT}:3000"
    environment:
      PATH: '$PATH:/rails/bin'
      APP_VERSION: ${APP_VERSION:-latest}
    networks:
      - be_the_golf_network
networks:
  be_the_golf_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}

